theme: jekyll-theme-dinky
title: lectures
description: Lectures and study material
github:
    owner_name: Martin Di Paola
    owner_url: https://github.com/eldipa
    repository_name: lectures
    repository_url: https://github.com/eldipa/lectures
